# Set name of your application
application: Awesome

# Set to some reasonably safe password. Requests are authorized by this.
token: ~
# Full path to your Rails application, eg. "/var/www/my_rails_app"
path:  ~
# a repository that's set up to git pull
repository: ~

# Send notifications to Twitter
# You'll probably want to protect the updates for this account
twitter:
  username: ~
  password: ~

cap:
  action: "deploy"
