# * Set name of your application
application: Awesome

# * Username/password for HTTP Auth
username: ~
password: ~

# * Full path to your Rails application, eg. "/var/www/my_rails_app"
path:  ~

# * Capistrano command (defaults to `cap deploy:migrations` if not set)
cap_command: ~
